%% anc_CPR_preProcessDATA
try
     cd('./matlab_scripts/')
    
catch
end

addpath(genpath('./readData'))
  SESSION_list = dir(['./test_data/' '*.mwk']);

for j = 1:length(SESSION_list)
    filename = ['./test_data/' SESSION_list(j).name];
    
    data = MW_readFile(filename, ...
        {'ML_trialStart',...
        'ML_trialEnd',...
        'RDP_coherence',...
        'RDP_direction',...
        'n_alpha',...
        'alpha',...
        'target_x',...
        'target_y',...
        'IO_target_size',...
        'IO_target_ON',...
        'IO_target_shown',...
        'IO_target_phase',...
        'IO_cursor_x',...
        'IO_cursor_y',...
        'IO_target_flag',...
        'EXP_shiftType', ....
        'EXP_shiftFrames', ...
        'EXP_stepsize', ...
        'TRIAL_outcome'},{});
    
    movefile(([filename,'.mat']),([pwd,'/',filename]))
    
end

sound(sin(1:3000));
